/*
 * Copyright (c) 2022. Glowbuzzer. All rights reserved
 */

export enum GlowbuzzerTileIdentifiers {
    CONNECT = "CONNECT",
    CONFIG_EDIT = "CONFIG_EDIT",
    JOG_CARTESIAN = "CARTESIAN_JOG",
    JOG_JOINT = "JOINT_JOG",
    THREE_DIMENSIONAL_SCENE = "THREE_DIMENSIONAL_SCENE",
    GCODE = "GCODE",
    FEEDRATE = "FEEDRATE",
    SPINDLE = "SPINDLE",
    DIGITAL_INPUTS = "DIGITAL_INPUTS",
    ANALOG_INPUTS = "ANALOG_INPUTS",
    INTEGER_INPUTS = "INTEGER_INPUTS",
    DIGITAL_OUTPUTS = "DIGITAL_OUTPUTS",
    ANALOG_OUTPUTS = "ANALOG_OUTPUTS",
    INTEGER_OUTPUTS = "INTEGER_OUTPUTS",
    CARTESIAN_DRO = "CARTESIAN_DRO",
    JOINT_DRO = "JOINT_DRO",
    JOINT_TORQUE_MODES = "JOINT_TORQUE_MODES",
    FRAMES = "FRAMES",
    POINTS = "POINTS",
    TOOLS = "TOOLS",
    TASKS = "TASKS",
    TELEMETRY = "TELEMETRY",
    STATE_MACHINE_TOOLS = "STATE_MACHINE_TOOLS",
    EMSTAT = "EMSTAT"
}
