export const alTable = {
    0: "No error",
    1: "Unspecified error",
    2: "No memory",
    17: "Invalid requested state change",
    18: "Unknown requested state",
    19: "Bootstrap not supported",
    20: "No valid firmware",
    21: "Invalid mailbox configuration",
    22: "Invalid mailbox configuration",
    23: "Invalid sync manager configuration",
    24: "No valid inputs available",
    25: "No valid outputs",
    26: "Synchronization error",
    27: "Sync manager watchdog",
    28: "Invalid sync Manager types",
    29: "Invalid output configuration",
    30: "Invalid input configuration",
    31: "Invalid watchdog configuration",
    32: "Slave needs cold start",
    33: "Slave needs INIT",
    34: "Slave needs PREOP",
    35: "Slave needs SAFEOP",
    36: "Invalid input mapping",
    37: "Invalid output mapping",
    38: "Inconsistent settings",
    39: "Freerun not supported",
    40: "Synchronisation not supported",
    41: "Freerun needs 3buffer mode",
    42: "Background watchdog",
    43: "No valid Inputs and Outputs",
    44: "Fatal sync error",
    45: "No sync error",
    46: "Invalid input FMMU configuration",
    48: "Invalid DC SYNC configuration",
    49: "Invalid DC latch configuration",
    50: "PLL error",
    51: "DC sync IO error",
    52: "DC sync timeout error",
    53: "DC invalid sync cycle time",
    54: "DC invalid sync0 cycle time",
    55: "DC invalid sync1 cycle time",
    65: "MBX_AOE",
    66: "MBX_EOE",
    67: "MBX_COE",
    68: "MBX_FOE",
    69: "MBX_SOE",
    79: "MBX_VOE",
    80: "EEPROM no access",
    81: "EEPROM error",
    96: "Slave restarted locally",
    97: "Device identification value updated",
    240: "Application controller available",
    65535: "Unknown"
}


export const slaveStateTable = {
    0: "EC State: None",
    1: "EC State: Init",
    2: "EC State: Pre-op",
    3: "EC State: Boot",
    4: "EC State: Safe-op",
    8: "EC State: Operational",
    16: "EC State: Error Ack",
    17: "EC State: Init error active",
    18: "EC State: Pre-op error active",
    24: "EC State: Safe-op error active",
    32: "EC State: ?"
}
