name: Deployment
on:
    push:
        branches:
            - site
jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
            -   uses: actions/checkout@v1

            -   name: Cache pnpm modules
                uses: actions/cache@v2
                with:
                    path: ~/.pnpm-store
                    key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                    restore-keys: |
                        ${{ runner.os }}-

            -   uses: actions/setup-node@v1
                with:
                    node-version: "12.x"

            -   uses: pnpm/action-setup@v2.0.1
                with:
                    version: 6.13.0

            -   name: Install packages
                run: pnpm install --no-optional

            -   name: Build site
                run: pnpm run build:glowsite

            -   name: Deploy site
                run: ./deploy-site.sh glowbuzzer-www-internal E37J47Y7NXA5BD
                env:
                    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    BUILD_NUM: 1.${{ github.run_number }}
