name: Publish alpha npm packages
on:
    push:
        branches:
            - main
        paths:
            - ".github/workflows/publish-packages.yml"
            - ".github/workflows/publish-packages-alpha.yml"
            - "package.json"
            - "libs/**"
            - "build.mjs"

jobs:
    publish:
        uses: ./.github/workflows/publish-packages.yml
        with:
            tag: alpha
            version: alpha-${{ github.run_number }}
        secrets: inherit
