name: Publish alpha npm packages
on:
    workflow_dispatch:

    push:
        branches:
            # we don't publish on every commit any more
            #            - main
            - not_currently_activated
        paths:
            - ".github/workflows/publish-packages.yml"
            - ".github/workflows/publish-packages-alpha.yml"
            - "package.json"
            - "libs/**"
            - "build.mjs"

jobs:
    publish:
        uses: ./.github/workflows/publish-packages.yml
        with:
            tag: alpha
            version: 0.0.0-alpha.${{ github.run_number }}
        secrets: inherit
