name: Publish examples/generic
on:
    push:
        branches:
            - main
        paths:
            - ".github/workflows/publish-examples-generic.yml"
            - ".github/workflows/publish-example.yml"
            - "package.json"
            - "libs/**"
            - "examples/generic/**"

jobs:
    publish:
        uses: ./.github/workflows/publish-example.yml
        with:
            example: generic
            site: www.glowbuzzer.com
            distribution: E284GBH6OG76DV
        secrets: inherit
