# Reusable workflow to publish example app to preview or www.glowbuzzer.com
# used by publish-example-generic and publish-example-staubli, and release-please

name: Publish app example
on:
    workflow_call:
        inputs:
            example:
                # which example to build/publish
                required: true
                type: string
            site:
                # website address
                required: true
                type: string
            distribution:
                # cloudfront distribution id
                required: true
                type: string

jobs:
    deploy:
        runs-on: ubuntu-22.04
        steps:
            -   uses: actions/checkout@v1

            -   uses: pnpm/action-setup@v2.2.2
                with:
                    version: 6

            -   uses: actions/setup-node@v3
                with:
                    node-version: 16
                    cache: pnpm

            -   name: Install packages
                run: pnpm install

            -   name: Build app
                run: ./node_modules/.bin/nx build ${{ inputs.example }} --baseHref=/examples/${{ inputs.example }}/

            -   name: Deploy site
                run: ./examples/deploy-example.sh ${{ inputs.example }} ${{ inputs.site }} ${{ inputs.distribution }}
                env:
                    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
