name: Publish examples/staubli
on:
    push:
        branches:
            - main
        paths:
            - ".github/workflows/publish-examples-staubli.yml"
            - "package.json"
            - "libs/**"
            - "examples/staubli/**"

jobs:
    publish:
        uses: ./.github/workflows/publish-example.yml
        with:
            example: staubli
            site: www.glowbuzzer.com
            distribution: E284GBH6OG76DV
        secrets: inherit
