name: Publish GBR Test Code
on:
    push:
        branches:
            - main
        paths:
            - ".github/workflows/publish-test-code.yml"
            - "package.json"
            - "pnpm-lock.yaml"
            - "libs/**"
            - "test/**"

jobs:
    deploy:
        runs-on: ubuntu-22.04
        steps:
            -   uses: actions/checkout@v4

            -   uses: actions/setup-node@v4
                with:
                    node-version: 18

            -   uses: pnpm/action-setup@v4
                with:
                    version: 8

            -   name: Install packages
                run: pnpm install

            -   name: Build test code
                run: node test/build.mjs --outfile test.js --source test/index.ts

            -   name: Deploy code
                run: sh ./test/deploy-test.sh downloads.glowbuzzer.com E36QR0RH2CR6EK
                env:
                    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
