name: Publish alpha npm packages
on:
    push:
        branches:
            - main
        paths:
            - "libs/**"
            - ".github/**"
            - "build.mjs"
            - "package.json"

jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
            -   uses: actions/checkout@v1

            -   name: Cache pnpm modules
                uses: actions/cache@v2
                with:
                    path: ~/.pnpm-store
                    key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                    restore-keys: |
                        ${{ runner.os }}-

            -   uses: actions/setup-node@v1
                with:
                    node-version: "14.x"

            -   uses: pnpm/action-setup@v2.0.1
                with:
                    version: 6.13.0

            -   name: Install packages
                run: pnpm install # --no-optional

            -   name: Package libs
                run: node build.mjs controls,store 1.0.1-alpha.${{ github.run_number }}

            -   name: Generate react component docs
                run: node_modules/.bin/react-docgen -x tsx -o dist/controls/component-docs.json libs/controls/src

            -   name: Publish dist/controls
                run: npm publish dist/controls
                env:
                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            -   name: Publish dist/store
                run: npm publish dist/store
                env:
                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            -   name: Publish dist/layout
                run: npm publish dist/layout
                env:
                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

