name: Publish RELEASE examples/staubli
on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
            -   uses: actions/checkout@v1

            -   uses: actions/setup-node@v1
                with:
                    node-version: "14.x"

            -   uses: pnpm/action-setup@v2.0.1
                with:
                    version: 6.13.0

            -   name: Install packages
                run: pnpm install

            -   name: Build app
                run: ./node_modules/.bin/nx build staubli --baseHref=/examples/staubli/

            -   name: Deploy site
                run: ./examples/deploy-example.sh staubli www.glowbuzzer.com EOLCC9H61HP6F
                env:
                    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
