name: Publish examples/staubli
on:
    push:
        branches:
            # disabled for now - would require refactoring to get working
            - none
        paths:
            - ".github/workflows/publish-example-preview-staubli.yml"
            - ".github/workflows/publish-example.yml"
            - "package.json"
            - "libs/**"
            - "examples/machines/staubli/**"
            - "examples/deploy-example.sh"

jobs:
    publish:
        uses: ./.github/workflows/publish-example.yml
        with:
            example: staubli
            site: preview.glowbuzzer.com
            distribution: E284GBH6OG76DV
        secrets: inherit
