###
# Does a partial build to check that release build is likely to succeed. Detects issues with bundling and docgen
###

on:
    push:
        branches:
            - main

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
    verify:
        runs-on: ubuntu-22.04
        steps:
            -   uses: actions/checkout@v4

            -   uses: pnpm/action-setup@v4
                with:
                    version: 9

            -   uses: actions/setup-node@v4
                with:
                    node-version: 20

            -   name: Install packages
                run: pnpm install --frozen-lockfile

            -   name: Package libs
                run: node build.mjs controls,store 0.0.0

            -   name: Verify react component docs
                run: node react-docgen-verify.mjs

            -   name: Verify typedoc
                run: node typedoc-verify.mjs
